### ISSUE TITLE
wireless network icons too dark

### ISSUE THREAD

**Issue by drreynolds** [UbuntuBudgie/pocillo#33] opened 2017-06-20 18:47 UTC
With the default dark panel in Budgie, the dark icons for the network manager make it nearly invisible.  I realize that this is because Pocillo derives from Faba, but it would be great if Pocillo replaced those overly-dark icons with something better.

**Comment by fossfreedom** [comment] 2017-06-21 10:36
thoughts @Foggalong ?

**Comment by fossfreedom** [comment] 2017-06-26 12:02
BTW @drreynolds what is the panel size you are using?  Network-manager applet cannot scale the icon size if the panel is too small and defaults to a dark icon.  Panel size should be approx 37px in size.

**Comment by drreynolds** [comment] 2017-06-26 16:00
I see.  I prefer a smaller panel (32px).  Is it not possible to have the
smaller panel also default to the brighter icons?

-- 

 Daniel R. Reynolds
 Associate Professor
 Mathematics @ SMU
 214-768-4339
 http://faculty.smu.edu/reynolds/

**Comment by fossfreedom** [comment] 2017-06-26 18:57
The issue is actually with network-manager itself.  The icons are fixed in size - when the panel shrinks network manager itself stops displaying some of the icons (the bright ones) before not displaying others.

I suppose you could manually shrink the icons yourself for your chosen icon theme - these are the icon names.  No idea if that works.

https://git.gnome.org/browse/network-manager-applet/tree/icons/22

Better would be a non-system tray version of nm-applet.  That will need to be created by an awesome dev.

**Comment by Foggalong** [comment] 2017-07-20 20:57
@fossfreedom I don't think that's actually what's causing this. I've attached screenshots of the icon I think is the problem below (correct me if I'm wrong @drreynolds).

| With Faba-Mono | Without Faba-Mono |
| --- | --- |
| ![screenshot_2017-07-20_21-53-01](https://user-images.githubusercontent.com/5920259/28438371-d25f391c-6d95-11e7-84e1-f3112708cbbd.png) | ![screenshot_2017-07-20_21-52-38](https://user-images.githubusercontent.com/5920259/28438372-d264a7ee-6d95-11e7-9774-81f49008242b.png)

On the left is how it looks when Faba-Mono is involved in any way, be it through inherits or any sort of merge of the two themes. On the right is how it's supposed to look, and indeed does look if Moka, Faba, or Pocillo (git or packaged) is applied.

Makes me think there's some icon in Faba-Mono which isn't behaving how it's supposed to, so I'll have a look and see if I can route that out before merging #38.

**Comment by drreynolds** [comment] 2017-07-20 21:04
@Foggalong, that is precisely the problematic icon -- all of the other ones display with the 'bright' look no matter the panel size, but this one requires a 37px panel or larger to display correctly.

**Comment by fossfreedom** [comment] 2017-07-20 22:49
Yep - that is the correct style for faba-mono - its the wired connection style.

For faba-mono with a wireless icon it is slightly restyled.

![workspace 1_060](https://user-images.githubusercontent.com/996240/28442012-d6b99b50-6da5-11e7-89a7-25980f0fccc8.jpg)

As you can see shrinking the panel size does not affect the wireless icon.  So this is fixed in 17.10

**Comment by Foggalong** [comment] 2017-07-24 18:01
@fossfreedom I'm not entirely sure what it is you're saying but the panel size isn't the problem here, it's the icon being drawn on from Faba-Mono. For some reason  `network-wired.svg` uses the "disabled" colour for the entire icon which is why it's showing up darker.

![screenshot_2017-07-24_18-51-48](https://user-images.githubusercontent.com/5920259/28537005-57eecb52-70a1-11e7-8d3b-e9f3feed2a93.png)

If you correct it so that it uses the "enabled" colour then it shows up correctly in the panel.

![screenshot_2017-07-24_18-58-53](https://user-images.githubusercontent.com/5920259/28537327-56cca004-70a2-11e7-96bd-e131591254a2.png)

**Comment by fossfreedom** [comment] 2017-07-24 18:06
ah - ok - makes sense.  I was actually looking at the wireless icons.  Yeah - you are on the ball with the wired icon mismatch.

**Comment by Foggalong** [comment] 2017-07-24 18:09
Cool cools, will add that in then :+1:

**Closed** 2017-07-24 18:18 UTC
Labels: enhancement
